- hosts: localhost
  tasks:
    - name: Run a container
      community.docker.docker_container:
        name: "{{ image_name + '_container' }}"
        image: "{{ image_name }}:{{ image_tag | default('latest') }}"
        state: started